# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.5.7
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.regenerate_message_data import RegenerateMessageData

class TestRegenerateMessageData(unittest.TestCase):
    """RegenerateMessageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegenerateMessageData:
        """Test RegenerateMessageData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegenerateMessageData`
        """
        model = RegenerateMessageData()
        if include_optional:
            return RegenerateMessageData(
                highlight_citations = True,
                highlight_delimiters = [
                    ''
                    ],
                model = '',
                stream_response = True,
                topic_id = ''
            )
        else:
            return RegenerateMessageData(
                topic_id = '',
        )
        """

    def testRegenerateMessageData(self):
        """Test RegenerateMessageData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
