# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.5.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_python_client.models.edit_message_data import EditMessageData

class TestEditMessageData(unittest.TestCase):
    """EditMessageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditMessageData:
        """Test EditMessageData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditMessageData`
        """
        model = EditMessageData()
        if include_optional:
            return EditMessageData(
                highlight_citations = True,
                highlight_delimiters = [
                    ''
                    ],
                message_sort_order = 56,
                model = '',
                new_message_content = '',
                stream_response = True,
                topic_id = ''
            )
        else:
            return EditMessageData(
                message_sort_order = 56,
                new_message_content = '',
                topic_id = '',
        )
        """

    def testEditMessageData(self):
        """Test EditMessageData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
