# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.5.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_python_client.models.create_chunk_group_data import CreateChunkGroupData

class TestCreateChunkGroupData(unittest.TestCase):
    """CreateChunkGroupData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateChunkGroupData:
        """Test CreateChunkGroupData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateChunkGroupData`
        """
        model = CreateChunkGroupData()
        if include_optional:
            return CreateChunkGroupData(
                description = '',
                name = '',
                tracking_id = ''
            )
        else:
            return CreateChunkGroupData(
                description = '',
                name = '',
        )
        """

    def testCreateChunkGroupData(self):
        """Test CreateChunkGroupData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
