# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.6.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.recommend_group_chunks_request import RecommendGroupChunksRequest

class TestRecommendGroupChunksRequest(unittest.TestCase):
    """RecommendGroupChunksRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecommendGroupChunksRequest:
        """Test RecommendGroupChunksRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecommendGroupChunksRequest`
        """
        model = RecommendGroupChunksRequest()
        if include_optional:
            return RecommendGroupChunksRequest(
                filters = {"must":[{"field":"metadata.key2","match":["value3","value4"],"range":{"gt":0,"gte":0,"lt":1,"lte":1}}],"must_not":[{"field":"metadata.key3","match":["value5","value6"],"range":{"gt":0,"gte":0,"lt":1,"lte":1}}],"should":[{"field":"metadata.key1","match":["value1","value2"],"range":{"gt":0,"gte":0,"lt":1,"lte":1}}]},
                group_size = 0,
                limit = 0,
                negative_group_ids = [
                    ''
                    ],
                negative_group_tracking_ids = [
                    ''
                    ],
                positive_group_ids = [
                    ''
                    ],
                positive_group_tracking_ids = [
                    ''
                    ],
                slim_chunks = True,
                strategy = ''
            )
        else:
            return RecommendGroupChunksRequest(
        )
        """

    def testRecommendGroupChunksRequest(self):
        """Test RecommendGroupChunksRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
