# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.5.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_python_client.models.upload_file_data import UploadFileData

class TestUploadFileData(unittest.TestCase):
    """UploadFileData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadFileData:
        """Test UploadFileData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadFileData`
        """
        model = UploadFileData()
        if include_optional:
            return UploadFileData(
                base64_file = '',
                create_chunks = True,
                description = '',
                file_mime_type = '',
                file_name = '',
                link = '',
                metadata = None,
                tag_set = [
                    ''
                    ],
                time_stamp = ''
            )
        else:
            return UploadFileData(
                base64_file = '',
                file_mime_type = '',
                file_name = '',
        )
        """

    def testUploadFileData(self):
        """Test UploadFileData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
