# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.5.7
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.chunk_filter import ChunkFilter

class TestChunkFilter(unittest.TestCase):
    """ChunkFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChunkFilter:
        """Test ChunkFilter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChunkFilter`
        """
        model = ChunkFilter()
        if include_optional:
            return ChunkFilter(
                must = [
                    {"field":"metadata.key1","match":["value1","value2"],"range":{"gt":0,"gte":0,"lt":1,"lte":1}}
                    ],
                must_not = [
                    {"field":"metadata.key1","match":["value1","value2"],"range":{"gt":0,"gte":0,"lt":1,"lte":1}}
                    ],
                should = [
                    {"field":"metadata.key1","match":["value1","value2"],"range":{"gt":0,"gte":0,"lt":1,"lte":1}}
                    ]
            )
        else:
            return ChunkFilter(
        )
        """

    def testChunkFilter(self):
        """Test ChunkFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
