# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.8.5
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.autocomplete_data import AutocompleteData

class TestAutocompleteData(unittest.TestCase):
    """AutocompleteData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutocompleteData:
        """Test AutocompleteData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutocompleteData`
        """
        model = AutocompleteData()
        if include_optional:
            return AutocompleteData(
                content_only = True,
                filters = {"must":[{"field":"metadata.key2","match":["value3","value4"],"range":{"gt":0.0,"gte":0.0,"lt":1.0,"lte":1.0}}],"must_not":[{"field":"metadata.key3","match":["value5","value6"],"range":{"gt":0.0,"gte":0.0,"lt":1.0,"lte":1.0}}],"should":[{"field":"metadata.key1","match":["value1","value2"],"range":{"gt":0.0,"gte":0.0,"lt":1.0,"lte":1.0}}]},
                highlight_delimiters = [
                    ''
                    ],
                highlight_results = True,
                highlight_threshold = 1.337,
                page_size = 0,
                query = '',
                recency_bias = 1.337,
                score_threshold = 1.337,
                search_type = '',
                slim_chunks = True,
                tag_weights = {
                    'key' : 1.337
                    },
                use_weights = True
            )
        else:
            return AutocompleteData(
                query = '',
                search_type = '',
        )
        """

    def testAutocompleteData(self):
        """Test AutocompleteData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
