# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.5.7
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_py_client.models.update_group_by_tracking_id_data import UpdateGroupByTrackingIDData

class TestUpdateGroupByTrackingIDData(unittest.TestCase):
    """UpdateGroupByTrackingIDData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateGroupByTrackingIDData:
        """Test UpdateGroupByTrackingIDData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateGroupByTrackingIDData`
        """
        model = UpdateGroupByTrackingIDData()
        if include_optional:
            return UpdateGroupByTrackingIDData(
                description = '',
                name = '',
                tracking_id = ''
            )
        else:
            return UpdateGroupByTrackingIDData(
                tracking_id = '',
        )
        """

    def testUpdateGroupByTrackingIDData(self):
        """Test UpdateGroupByTrackingIDData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
