# coding: utf-8

"""
    Trieve API

    Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.

    The version of the OpenAPI document: 0.5.0
    Contact: developers@trieve.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from trieve_python_client.models.search_over_groups_response_body import SearchOverGroupsResponseBody

class TestSearchOverGroupsResponseBody(unittest.TestCase):
    """SearchOverGroupsResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchOverGroupsResponseBody:
        """Test SearchOverGroupsResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchOverGroupsResponseBody`
        """
        model = SearchOverGroupsResponseBody()
        if include_optional:
            return SearchOverGroupsResponseBody(
                group_chunks = [
                    trieve_python_client.models.group_score_chunk_dto.GroupScoreChunkDTO(
                        group_id = '', 
                        metadata = [
                            {"metadata":[{"chunk_html":"<p>Some HTML content</p>","content":"Some content","id":"d290f1ee-6c54-4b01-90e6-d701748f0851","link":"https://example.com","metadata":{"key1":"value1","key2":"value2"},"time_stamp":"2021-01-01T00:00:00","weight":0.5}],"score":0.5}
                            ], )
                    ],
                total_chunk_pages = 56
            )
        else:
            return SearchOverGroupsResponseBody(
                group_chunks = [
                    trieve_python_client.models.group_score_chunk_dto.GroupScoreChunkDTO(
                        group_id = '', 
                        metadata = [
                            {"metadata":[{"chunk_html":"<p>Some HTML content</p>","content":"Some content","id":"d290f1ee-6c54-4b01-90e6-d701748f0851","link":"https://example.com","metadata":{"key1":"value1","key2":"value2"},"time_stamp":"2021-01-01T00:00:00","weight":0.5}],"score":0.5}
                            ], )
                    ],
                total_chunk_pages = 56,
        )
        """

    def testSearchOverGroupsResponseBody(self):
        """Test SearchOverGroupsResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
