{
  "openapi": "3.0.3",
  "info": {
    "title": "Trieve API",
    "description": "Trieve OpenAPI Specification. This document describes all of the operations available through the Trieve API.",
    "contact": {
      "name": "Trieve Team",
      "url": "https://trieve.ai",
      "email": "developers@trieve.ai"
    },
    "license": {
      "name": "BSL",
      "url": "https://github.com/devflowinc/trieve/blob/main/LICENSE.txt"
    },
    "version": "0.6.0"
  },
  "servers": [
    {
      "url": "https://api.trieve.ai",
      "description": "Production server"
    },
    {
      "url": "http://localhost:8090",
      "description": "Local development server"
    }
  ],
  "paths": {
    "/api/auth": {
      "get": {
        "tags": [
          "auth"
        ],
        "summary": "Login",
        "description": "Login\n\nThis will redirect you to the OAuth provider for authentication with email/pass, SSO, Google, Github, etc.",
        "operationId": "login"
      },
      "delete": {
        "tags": [
          "auth"
        ],
        "summary": "Logout",
        "description": "Logout\n\nInvalidate your current auth credential stored typically stored in a cookie. This does not invalidate your API key.",
        "operationId": "logout"
      }
    },
    "/api/auth/callback": {
      "get": {
        "tags": [
          "auth"
        ],
        "summary": "OpenID Connect callback",
        "description": "OpenID Connect callback\n\nThis is the callback route for the OAuth provider, it should not be called directly. Redirects to browser with set-cookie header.",
        "operationId": "callback"
      }
    },
    "/api/auth/me": {
      "get": {
        "tags": [
          "auth"
        ],
        "summary": "Get Me",
        "description": "Get Me\n\nGet the user corresponding to your current auth credentials.",
        "operationId": "get_me",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk": {
      "post": {
        "tags": [
          "chunk"
        ],
        "summary": "Create or Upsert Chunk or Chunks",
        "description": "Create or Upsert Chunk or Chunks\n\nCreate a new chunk. If the chunk has the same tracking_id as an existing chunk, the request will fail. Once a chunk is created, it can be searched for using the search endpoint.",
        "operationId": "create_chunk",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "chunk"
        ],
        "summary": "Update Chunk",
        "description": "Update Chunk\n\nUpdate a chunk. If you try to change the tracking_id of the chunk to have the same tracking_id as an existing chunk, the request will fail.",
        "operationId": "update_chunk",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk/gen_suggestions": {
      "post": {
        "tags": [
          "chunk"
        ],
        "summary": "Generate suggested queries",
        "description": "Generate suggested queries\n\nThis endpoint will generate 3 suggested queries based off the query provided in the request body and return them as a JSON object.",
        "operationId": "create_suggested_queries_handler",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/generate": {
      "post": {
        "tags": [
          "chunk"
        ],
        "summary": "RAG on Specified Chunks",
        "description": "RAG on Specified Chunks\n\nThis endpoint exists as an alternative to the topic+message concept where our API handles chat memory. With this endpoint, the user is responsible for providing the context window and the prompt. See more in the \"search before generate\" page at docs.trieve.ai.",
        "operationId": "generate_off_chunks",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/recommend": {
      "post": {
        "tags": [
          "chunk"
        ],
        "summary": "Get Recommended Chunks",
        "description": "Get Recommended Chunks\n\nGet recommendations of chunks similar to the chunks in the request. Think about this as a feature similar to the \"add to playlist\" recommendation feature on Spotify. This request pairs especially well with our groups endpoint.",
        "operationId": "get_recommended_chunks",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/search": {
      "post": {
        "tags": [
          "chunk"
        ],
        "summary": "Search",
        "description": "Search\n\nThis route provides the primary search functionality for the API. It can be used to search for chunks by semantic similarity, full-text similarity, or a combination of both. Results' `chunk_html` values will be modified with `<b>` tags for sub-sentence highlighting.",
        "operationId": "search_chunk",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk/tracking_id/update": {
      "put": {
        "tags": [
          "chunk"
        ],
        "summary": "Update Chunk By Tracking Id",
        "description": "Update Chunk By Tracking Id\n\nUpdate a chunk by tracking_id. This is useful for when you are coordinating with an external system and want to use the tracking_id to identify the chunk.",
        "operationId": "update_chunk_by_tracking_id",
        "deprecated": true,
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk/tracking_id/{tracking_id}": {
      "get": {
        "tags": [
          "chunk"
        ],
        "summary": "Get Chunk By Tracking Id",
        "description": "Get Chunk By Tracking Id\n\nGet a singular chunk by tracking_id. This is useful for when you are coordinating with an external system and want to use your own id as the primary reference for a chunk.",
        "operationId": "get_chunk_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "chunk"
        ],
        "summary": "Delete Chunk By Tracking Id",
        "description": "Delete Chunk By Tracking Id\n\nDelete a chunk by tracking_id. This is useful for when you are coordinating with an external system and want to use the tracking_id to identify the chunk. If deleting a root chunk which has a collision, the most recently created collision will become a new root chunk.",
        "operationId": "delete_chunk_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk/{chunk_id}": {
      "get": {
        "tags": [
          "chunk"
        ],
        "summary": "Get Chunk By Id",
        "description": "Get Chunk By Id\n\nGet a singular chunk by id.",
        "operationId": "get_chunk_by_id",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "chunk"
        ],
        "summary": "Delete Chunk",
        "description": "Delete Chunk\n\nDelete a chunk by its id. If deleting a root chunk which has a collision, the most recently created collision will become a new root chunk.",
        "operationId": "delete_chunk",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group": {
      "post": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Create Chunk Group",
        "description": "Create Chunk Group\n\nCreate a new chunk_group. This is a way to group chunks together. If you try to create a chunk_group with the same tracking_id as an existing chunk_group, this operation will fail.",
        "operationId": "create_chunk_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Update Group",
        "description": "Update Group\n\nUpdate a chunk_group. If you try to change the tracking_id to one that already exists, this operation will fail.",
        "operationId": "update_chunk_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/chunk/{group_id}": {
      "post": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Add Chunk to Group",
        "description": "Add Chunk to Group\n\nRoute to add a chunk to a group.",
        "operationId": "add_chunk_to_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Remove Chunk from Group",
        "description": "Remove Chunk from Group\n\nRoute to remove a chunk from a group.",
        "operationId": "remove_chunk_from_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/chunks": {
      "post": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Get Groups for Chunks",
        "description": "Get Groups for Chunks\n\nRoute to get the groups that a chunk is in.",
        "operationId": "get_groups_chunk_is_in",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/group_oriented_search": {
      "post": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Search Over Groups",
        "description": "Search Over Groups\n\nThis route allows you to get groups as results instead of chunks. Each group returned will have the matching chunks sorted by similarity within the group. This is useful for when you want to get groups of chunks which are similar to the search query. If choosing hybrid search, the results will be re-ranked using BAAI/bge-reranker-large. Compatible with semantic, fulltext, or hybrid search modes.",
        "operationId": "search_over_groups",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/recommend": {
      "post": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Get Recommended Groups",
        "description": "Get Recommended Groups\n\nRoute to get recommended groups. This route will return groups which are similar to the groups in the request body.",
        "operationId": "get_recommended_groups",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/search": {
      "post": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Search Within Group",
        "description": "Search Within Group\n\nThis route allows you to search only within a group. This is useful for when you only want search results to contain chunks which are members of a specific group. If choosing hybrid search, the results will be re-ranked using BAAI/bge-reranker-large.",
        "operationId": "search_within_group",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/tracking_id/{group_tracking_id}/{page}": {
      "get": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Get Chunks in Group by Tracking ID",
        "description": "Get Chunks in Group by Tracking ID\n\nRoute to get all chunks for a group. The response is paginated, with each page containing 10 chunks. Support for custom page size is coming soon. Page is 1-indexed.",
        "operationId": "get_chunks_in_group_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/tracking_id/{tracking_id}": {
      "get": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Get Group by Tracking ID",
        "description": "Get Group by Tracking ID\n\nFetch the group with the given tracking id.\nget_group_by_tracking_id",
        "operationId": "get_group_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Add Chunk to Group by Tracking ID",
        "description": "Add Chunk to Group by Tracking ID\n\nRoute to add a chunk to a group by tracking id.",
        "operationId": "add_chunk_to_group_by_tracking_id",
        "deprecated": true,
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Update Group by Tracking ID",
        "description": "Update Group by Tracking ID\n\nUpdate a chunk_group with the given tracking id.",
        "operationId": "update_group_by_tracking_id",
        "deprecated": true,
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Delete Group by Tracking ID",
        "description": "Delete Group by Tracking ID\n\nDelete a chunk_group with the given tracking id.",
        "operationId": "delete_group_by_tracking_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/{group_id}": {
      "get": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Get Group",
        "description": "Get Group\n\nFetch the group with the given id.\nget_group",
        "operationId": "get_chunk_group",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Delete Group",
        "description": "Delete Group\n\nThis will delete a chunk_group. If you set delete_chunks to true, it will also delete the chunks within the group.",
        "operationId": "delete_chunk_group",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/chunk_group/{group_id}/{page}": {
      "get": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Get Chunks in Group",
        "description": "Get Chunks in Group\n\nRoute to get all chunks for a group. The response is paginated, with each page containing 10 chunks. Page is 1-indexed.",
        "operationId": "get_chunks_in_group",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/dataset": {
      "post": {
        "tags": [
          "dataset"
        ],
        "summary": "Create dataset",
        "description": "Create dataset\n\nCreate a new dataset. The auth'ed user must be an owner of the organization to create a dataset.",
        "operationId": "create_dataset",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "dataset"
        ],
        "summary": "Update Dataset",
        "description": "Update Dataset\n\nUpdate a dataset. The auth'ed user must be an owner of the organization to update a dataset.",
        "operationId": "update_dataset",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/dataset/envs": {
      "get": {
        "tags": [
          "dataset"
        ],
        "summary": "Get Client Configuration",
        "description": "Get Client Configuration\n\nGet the client configuration for a dataset. Will use the TR-D",
        "operationId": "get_client_dataset_config",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/dataset/files/{dataset_id}/{page}": {
      "get": {
        "tags": [
          "file"
        ],
        "summary": "Get Files for Dataset",
        "description": "Get Files for Dataset\n\nGet all files which belong to a given dataset specified by the dataset_id parameter. 10 files are returned per page.",
        "operationId": "get_dataset_files_handler",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/dataset/groups/{dataset_id}/{page}": {
      "get": {
        "tags": [
          "chunk_group"
        ],
        "summary": "Get Groups for Dataset",
        "description": "Get Groups for Dataset\n\nFetch the groups which belong to a dataset specified by its id.",
        "operationId": "get_specific_dataset_chunk_groups",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/dataset/organization/{organization_id}": {
      "get": {
        "tags": [
          "dataset"
        ],
        "summary": "Get Datasets from Organization",
        "description": "Get Datasets from Organization\n\nGet all datasets for an organization. The auth'ed user must be an admin or owner of the organization to get its datasets.",
        "operationId": "get_datasets_from_organization",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/dataset/{dataset_id}": {
      "get": {
        "tags": [
          "dataset"
        ],
        "summary": "Get Dataset",
        "description": "Get Dataset\n\nGet a dataset by id. The auth'ed user must be an admin or owner of the organization to get a dataset.",
        "operationId": "get_dataset",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "dataset"
        ],
        "summary": "Delete Dataset",
        "description": "Delete Dataset\n\nDelete a dataset. The auth'ed user must be an owner of the organization to delete a dataset.",
        "operationId": "delete_dataset",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/events": {
      "post": {
        "tags": [
          "events"
        ],
        "summary": "Get events for the dataset",
        "description": "Get events for the dataset\n\nGet events for the dataset specified by the TR-Dataset header.",
        "operationId": "get_events",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/file": {
      "post": {
        "tags": [
          "file"
        ],
        "summary": "Upload File",
        "description": "Upload File\n\nUpload a file to S3 attached to the server. The file will be converted to HTML with tika and chunked algorithmically, images will be OCR'ed with tesseract. The resulting chunks will be indexed and searchable. Optionally, you can only upload the file and manually create chunks associated to the file after. See docs.trieve.ai and/or contact us for more details and tips. Auth'ed user must be an admin or owner of the dataset's organization to upload a file.",
        "operationId": "upload_file_handler",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/file/{file_id}": {
      "get": {
        "tags": [
          "file"
        ],
        "summary": "Get File",
        "description": "Get File\n\nDownload a file based on its id.",
        "operationId": "get_file_handler",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "file"
        ],
        "summary": "Delete File",
        "description": "Delete File\n\nDelete a file from S3 attached to the server based on its id. This will disassociate chunks from the file, but only delete them all together if you specify delete_chunks to be true. Auth'ed user must be an admin or owner of the dataset's organization to delete a file.",
        "operationId": "delete_file_handler",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/health": {
      "get": {
        "tags": [
          "health"
        ],
        "summary": "Health Check",
        "description": "Health Check\n\nConfirmation that the service is healthy and can make embedding vectors",
        "operationId": "health_check"
      }
    },
    "/api/invitation": {
      "post": {
        "tags": [
          "invitation"
        ],
        "summary": "Send Invitation",
        "description": "Send Invitation\n\nInvitations act as a way to invite users to join an organization. After a user is invited, they will automatically be added to the organization with the role specified in the invitation once they set their.",
        "operationId": "post_invitation",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/message": {
      "post": {
        "tags": [
          "message"
        ],
        "summary": "Create a message",
        "description": "Create a message\n\nCreate a message. Messages are attached to topics in order to coordinate memory of gen-AI chat sessions. We are considering refactoring this resource of the API soon. Currently, you can only send user messages. If the topic is a RAG topic then the response will include Chunks first on the stream. The structure will look like `[chunks]||mesage`. See docs.trieve.ai for more information.",
        "operationId": "create_message_completion_handler",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "message"
        ],
        "summary": "Edit a message",
        "description": "Edit a message\n\nEdit a message which exists within the topic's chat history. This will delete the message and replace it with a new message. The new message will be generated by the AI based on the new content provided in the request body. The response will include Chunks first on the stream if the topic is using RAG. The structure will look like `[chunks]||mesage`. See docs.trieve.ai for more information.",
        "operationId": "edit_message_handler",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "message"
        ],
        "summary": "Regenerate message",
        "description": "Regenerate message\n\nRegenerate the assistant response to the last user message of a topic. This will delete the last message and replace it with a new message. The response will include Chunks first on the stream if the topic is using RAG. The structure will look like `[chunks]||mesage`. See docs.trieve.ai for more information.",
        "operationId": "regenerate_message_handler",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/messages/{messages_topic_id}": {
      "get": {
        "tags": [
          "message"
        ],
        "summary": "Get all messages for a given topic",
        "description": "Get all messages for a given topic\n\nGet all messages for a given topic. If the topic is a RAG topic then the response will include Chunks first on each message. The structure will look like `[chunks]||mesage`. See docs.trieve.ai for more information.",
        "operationId": "get_all_topic_messages",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/organization": {
      "post": {
        "tags": [
          "organization"
        ],
        "summary": "Create Organization",
        "description": "Create Organization\n\nCreate a new organization. The auth'ed user who creates the organization will be the default owner of the organization.",
        "operationId": "create_organization",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "organization"
        ],
        "summary": "Update Organization",
        "description": "Update Organization\n\nUpdate an organization. Only the owner of the organization can update it.",
        "operationId": "update_organization",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/organization/usage/{organization_id}": {
      "get": {
        "tags": [
          "organization"
        ],
        "summary": "Get Organization Usage",
        "description": "Get Organization Usage\n\nFetch the current usage specification of an organization by its id. The auth'ed user must be an admin or owner of the organization to fetch it.",
        "operationId": "get_organization_usage",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/organization/users/{organization_id}": {
      "get": {
        "tags": [
          "organization"
        ],
        "summary": "Get Organization Users",
        "description": "Get Organization Users\n\nFetch the users of an organization by its id. The auth'ed user must be an admin or owner of the organization to fetch it.",
        "operationId": "get_organization_users",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/organization/{organization_id}": {
      "get": {
        "tags": [
          "organization"
        ],
        "summary": "Get Organization",
        "description": "Get Organization\n\nFetch the details of an organization by its id. The auth'ed user must be an admin or owner of the organization to fetch it.",
        "operationId": "get_organization_by_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "organization"
        ],
        "summary": "Delete Organization",
        "description": "Delete Organization\n\nDelete an organization by its id. The auth'ed user must be an owner of the organization to delete it.",
        "operationId": "delete_organization_by_id",
        "security": [
          {
            "ApiKey": [
              "admin"
            ]
          }
        ]
      }
    },
    "/api/stripe/payment_link/{plan_id}/{organization_id}": {
      "get": {
        "tags": [
          "stripe"
        ],
        "summary": "Checkout",
        "description": "Checkout\n\nGet a direct link to the stripe checkout page for the plan and organization",
        "operationId": "direct_to_payment_link"
      }
    },
    "/api/stripe/plans": {
      "get": {
        "tags": [
          "stripe"
        ],
        "summary": "Get All Plans",
        "description": "Get All Plans\n\nGet a list of all plans",
        "operationId": "get_all_plans"
      }
    },
    "/api/stripe/subscription/{subscription_id}": {
      "delete": {
        "tags": [
          "stripe"
        ],
        "summary": "Cancel Subscription",
        "description": "Cancel Subscription\n\nCancel a subscription by its id",
        "operationId": "cancel_subscription",
        "security": [
          {
            "ApiKey": [
              "owner"
            ]
          }
        ]
      }
    },
    "/api/stripe/subscription_plan/{subscription_id}/{plan_id}": {
      "patch": {
        "tags": [
          "stripe"
        ],
        "summary": "Update Subscription Plan",
        "description": "Update Subscription Plan\n\nUpdate a subscription to a new plan",
        "operationId": "update_subscription_plan",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/topic": {
      "post": {
        "tags": [
          "topic"
        ],
        "summary": "Create Topic",
        "description": "Create Topic\n\nCreate a new chat topic. Topics are attached to a user and act as a coordinator for memory of gen-AI chat sessions. We are considering refactoring this resource of the API soon.",
        "operationId": "create_topic",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "topic"
        ],
        "summary": "Update Topic",
        "description": "Update Topic\n\nUpdate an existing chat topic. Currently, only the name of the topic can be updated.",
        "operationId": "update_topic",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/topic/user/{user_id}": {
      "get": {
        "tags": [
          "topic"
        ],
        "summary": "Get All Topics for User",
        "description": "Get All Topics for User\n\nGet all topics belonging to a the auth'ed user. Soon, we plan to allow specification of the user for this route and include pagination.",
        "operationId": "get_all_topics_for_user",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/topic/{topic_id}": {
      "delete": {
        "tags": [
          "topic"
        ],
        "summary": "Delete Topic",
        "description": "Delete Topic\n\nDelete an existing chat topic. When a topic is deleted, all associated chat messages are also deleted.",
        "operationId": "delete_topic",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/user": {
      "put": {
        "tags": [
          "user"
        ],
        "summary": "Update User",
        "description": "Update User\n\nUpdate a user's information. If the user_id is not provided, the auth'ed user will be updated. If the user_id is provided, the auth'ed user must be an admin (1) or owner (2) of the organization.",
        "operationId": "update_user",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/user/delete_api_key/{api_key_id}": {
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Delete User Api Key",
        "description": "Delete User Api Key\n\nDelete an api key for the auth'ed user.",
        "operationId": "delete_user_api_key",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    },
    "/api/user/set_api_key": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Set User Api Key",
        "description": "Set User Api Key\n\nCreate a new api key for the auth'ed user. Successful response will contain the newly created api key. If a write role is assigned the api key will have permission level of the auth'ed user who calls this endpoint.",
        "operationId": "set_user_api_key",
        "security": [
          {
            "ApiKey": [
              "readonly"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKey": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization"
      }
    }
  },
  "tags": [
    {
      "name": "invitation",
      "description": "Invitation endpoint. Exists to invite users to an organization."
    },
    {
      "name": "auth",
      "description": "Authentication endpoint. Serves to register and authenticate users."
    },
    {
      "name": "user",
      "description": "User endpoint. Enables you to modify user roles and information."
    },
    {
      "name": "organization",
      "description": "Organization endpoint. Enables you to modify organization roles and information."
    },
    {
      "name": "dataset",
      "description": "Dataset endpoint. Datasets belong to organizations and hold configuration information for both client and server. Datasets contain chunks and chunk groups."
    },
    {
      "name": "chunk",
      "description": "Chunk endpoint. Think of chunks as individual searchable units of information. The majority of your integration will likely be with the Chunk endpoint."
    },
    {
      "name": "chunk_group",
      "description": "Chunk groups endpoint. Think of a chunk_group as a bookmark folder within the dataset."
    },
    {
      "name": "file",
      "description": "File endpoint. When files are uploaded, they are stored in S3 and broken up into chunks with text extraction from Apache Tika. You can upload files of pretty much any type up to 1GB in size. See chunking algorithm details at `docs.trieve.ai` for more information on how chunking works. Improved default chunking is on our roadmap."
    },
    {
      "name": "events",
      "description": "Notifications endpoint. Files are uploaded asynchronously and events are sent to the user when the upload is complete."
    },
    {
      "name": "topic",
      "description": "Topic chat endpoint. Think of topics as the storage system for gen-ai chat memory. Gen AI messages belong to topics."
    },
    {
      "name": "message",
      "description": "Message chat endpoint. Messages are units belonging to a topic in the context of a chat with a LLM. There are system, user, and assistant messages."
    },
    {
      "name": "stripe",
      "description": "Stripe endpoint. Used for the managed SaaS version of this app. Eventually this will become a micro-service. Reach out to the team using contact info found at `docs.trieve.ai` for more information."
    },
    {
      "name": "health",
      "description": "Health check endpoint. Used to check if the server is up and running."
    }
  ]
}